### ISSUE TITLE
Is the disparity smaller than real pixel movement

### ISSUE THREAD

**Issue by HydrogenSulfate** [mediaeng-lfv/LFV_Disparity_Estimation#1]
I test the disparity with a warping operation, but it is not correct when directly using the GT disparity, but is correct when using 32xdisp. Is there a scale factor between RGB image and disparity?

**Comment by catdance124** [comment]
Hi @HydrogenSulfate ,

Thank you for testing our disparity.  
I had overlooked whether there was a scale factor, so I looked that up.

Our data is based on [MPI Sintel](http://sintel.is.tue.mpg.de/depth), which says the following:
> the focal length as given by Blender, the hard-coded pixel dimensions of 32 px / mm  

Unfortunately, we had left the units of focal length in [mm].  
So, we need to convert the units of the focal length to [px].
```
disparity = (baseline[m] * focal_length[mm]) / depth[m]
  ↓
disparity = (baseline[m] * focal_length*32[px]) / depth[m]
```
That is to say, it is correct to use disparity x32 as you say.

Sincerely,  
Takahiro Kinoshita
