### ISSUE TITLE
Camera parameters for the scenes in the dataset

### ISSUE THREAD

**Issue by Sushobhan04** [mediaeng-lfv/LFV_Disparity_Estimation#2]
Does the dataset provide camera parameters for each scene ? I downloaded the Sintel_LFV_cross-hair.zip and couldn't find it. Is it present in the Sintel_LFV_9x9_with_all_disp.zip ? 

I wanted to confirm this before I download the whole dataset, which takes a lot of time.

**Comment by catdance124** [comment]
Hi @Sushobhan04 ,
Thank you for your interest in our dataset.

Unfortunately, camera parameters are not currently available even the Sintel_LFV_9x9_with_all_disp.zip.
Eventually, we hope to provide the camera parameters with reference to MPI Sintel.
> The extrinsic camera matrix is given by Blender, as the world matrix of the camera object.
> The intrinsic camera matrix is computed using the focal length as given by Blender, the hard-coded pixel dimensions of 32 px / mm, zero pixel skew, and the principal point at x = 511.5 and y = 217.5.
>> http://sintel.is.tue.mpg.de/depth

Please wait for a little while longer.
Sincerely,

**Comment by Duanener** [comment]
Hello，how could I get the extrinsic camera matrix？
