### ISSUE TITLE
About disparity map

### ISSUE THREAD

**Issue by backkon** [mediaeng-lfv/LFV_Disparity_Estimation#3]
Great work, but I have some questions. First of all, the disparity map is about between the central perspective and which perspective? Second, how can the disparity map be converted to a depth map? Looking forward to your reply!

**Comment by catdance124** [comment]
Hi @backkon ,
Thank you for your interest in our study.

1. > the disparity map is about between the central perspective and which perspective? 

The disparity map is about between the central perspective and the perspectives with baseline=0.01[m] away. That is, it is the top, bottom, left and right views adjacent to the central perspective.
Actually, the disparity maps were generated by inversely triangulating each pixel using the known focal length, depth for each pixel, and baseline distance.

Sorry for the unmaintained source code, but I think there are some hints here about disparity conversion. 
https://github.com/catdance124/sintel_light-field-video_rendering/blob/76513f605cea67c9528f8448a750b0bb2532699b/organize_rendering_data.py#L14
```python
def depth2disp(Z, baseline, focal_length):
    return baseline * focal_length / Z
```

2. > how can the disparity map be converted to a depth map?  

As mentioned above, the disparity map is generated using the depth map, the focal length, and the (fixed) baseline, so it should be possible to reverse the transformation. 
The focal length[mm] for each scene can be found here.
https://github.com/catdance124/sintel_light-field-video_rendering/blob/76513f605cea67c9528f8448a750b0bb2532699b/focal_length.csv

The first column of csv file corresponds to the name of the Sintel production file and can be mapped to the scene name in our dataset by referring to the following table.
| our Sintel dataset scene name | # MPI Sintel scene name | Sintel scene class | Sintel scene id |
|-------------------------------|-------------------------|--------------------|-----------------|
| ambushfight_1                 | ambush_1                | ambushfight        | 05.8d           |
| ambushfight_2                 | ambush_2                | ambushfight        | 05.8f           |
| ambushfight_3                 | ambush_3                | ambushfight        | 05.8g           |
| ambushfight_4                 | ambush_4                | ambushfight        | 05.8h           |
| ambushfight_5                 | ambush_5                | ambushfight        | 05.8i           |
| ambushfight_6                 | ambush_6                | ambushfight        | 05.8j           |
| bamboo_1                      | bamboo_1                | bamboo             | 05.2a           |
| bamboo_2                      | bamboo_2                | bamboo             | 05.2b           |
| bamboo_3                      | bamboo_3                | bamboo             | 05.2c           |
| chickenrun_1                  | market_4                | chickenrun         | 03.4a           |
| chickenrun_2                  | market_6                | chickenrun         | 03.4c           |
| chickenrun_3                  | market_1                | chickenrun         | 03.4e           |
| foggyrocks_1                  | tiger                   | foggyrocks         | 05.4a           |
| foggyrocks_2                  |                         | foggyrocks         | 05.4b           |
| questbegins_1                 | wall                    | questbegins        | 05.1b           |
| shaman_1                      |                         | shaman             | 02.a            |
| shaman_2                      |                         | shaman             | 02.b            |
| shaman_3                      | PERTURBED_shaman_1      | shaman             | 02.f            |
| shaman_b_1                    | shaman_3                | shaman_b           | 06.k            |
| thebigfight_1                 | cave_3                  | thebigfight        | 08.2l           |
| thebigfight_2                 |                         | thebigfight        | 08.2q           |
| thebigfight_3                 | cave_2                  | thebigfight        | 8.2g            |
| thebigfight_4                 | cave_4                  | thebigfight        | 8.2r            |

If you have any questions, please feel free to comment.
Sincerely,
