### ISSUE TITLE
Frame rate of dataset

### ISSUE THREAD

**Issue by gurdeepmaurya** [mediaeng-lfv/LFV_Disparity_Estimation#4]
Hi,

May I know the framerate of the dataset.

Thanks

**Comment by catdance124** [comment]
Hello.

The fps is 24.
It is set at rendering time by the following code.
```python
import bpy

scene = bpy.context.scene
scene.render.fps = 24
```
https://github.com/catdance124/sintel_light-field-video_rendering/blob/76513f605cea67c9528f8448a750b0bb2532699b/light_field_video_rendering.py#L20
*Sorry for the unmaintained source code.

We hope this will be helpful.
